language: ruby
rvm:
- 2.1

# install jekyll from gemfile
install: 
   - bundle install
   - rake
   - chmod +x ./scripts/build.sh
   - ./scripts/build.sh

# build site
scripts: true

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false