# Site settings
app-title: Start
title: College of Liberal Arts
title-link: https://liberalarts.temple.edu
description: ''

# Build settings
markdown: kramdown
permalink: pretty

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Travis bundles all gems in the vendor directory
# Jekyll will mistakenly read this and fail.
exclude: [vendor]